apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
#  namespace: default
  namespace: kubernetes-dashboard
spec:
  containers:
  - name: dnsutils
#    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    image: tutum/dnsutils
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

