apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv003
  labels:
    pv: nfs-pv003
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed-nfs-storage003
  nfs:
    path: /data/nfs003
    server: 172.16.0.3

