apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  containers:
    - name: myfrontend
      image: docker.io/nginx
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          scheme: HTTP
          path: /
          port: 80

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: nginx-service
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: nginx-service





