apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
spec:
  ports:
  - port: 8080
    nodePort: 8080
    targetPort: 8080
  selector:
    app: jira
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jira-headless
  labels:
    app: jira
spec:
  ports:
  - port: 8080
    name: jira-server
  clusterIP: None
  selector:
    app: jira
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pv-claim
  labels:
    app: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage003
  selector:
    matchLabels:
      pv: nfs-pv003
---
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
      name: jira
    spec:
      containers:
      - name: jira
        image: registry.cn-hangzhou.aliyuncs.com/mypaas/jira:7.13.0
        imagePullPolicy: Always
        volumeMounts:
        - name: jira-persistent-storage
          mountPath: /var/atlassian/jira        #jira数据目录
      volumes:
      - name: jira-persistent-storage
        persistentVolumeClaim:
          claimName: jira-pv-claim
